.TH addtoresources 1 "" "" gitlab-canvas-utils

.SH NAME
addtoresources - Adds students to GitLab repository containing course resources

.SH SYNOPSIS
.B addtoresources [OPTIONS]

.SH DESCRIPTION
Adds students to a specified GitLab repository that contains shared course
resources. A CSV produced by \fBroster\fP is required as input.

.SH OPTIONS
.TP
.BR -h ", " --help
display program help and usage

.TP
.BR -v ", " --verbose
enable verbose statistics about the adding of CruzIDs to the resources
repository (statistics printed to \fBstderr\fP).

.TP
.BR -c " " CSV ", " --csv=CSV
specify the path to the CSV containing the CruzIDs to add to the resources
repository default: \fBstdin\fP).

.TP
.BR -l " " LEVEL ", " --logging-level=LEVEL " " (default: " " info)
specify the \fBstderr\fP logging level (choices:
\fBdebug\fP, \fBinfo\fP, \fBwarning\fP, \fBerror\fP, \fBcritical\fP, \fBoff\fP).

.SH SEE ALSO
checkout(1),
clone(1),
createrepos(1),
roster(1)
