canvas_url = "https://canvas.ucsc.edu"
canvas_course_id = 472878
canvas_token = "<your token here>"
base_repo_path = "cse13s/winter2023/section01"
gitlab_server = "https://git.ucsc.edu"
gitlab_token = "<your token here>"
template_repo = "https://git.ucsc.edu/euchou/cse13s-template.git"
