#!/usr/bin/env python3

import os, csv, sys, toml, gitlab, argparse, logging

SERVER = "https://git.ucsc.edu"

repo_ops = {
    "access_created": 0,
    "access_updated": 0,
    "nouser": 0,
    "error": 0
}

roles = {
    "reporter": gitlab.REPORTER_ACCESS,
    "developer": gitlab.DEVELOPER_ACCESS,
    "maintainer": gitlab.MAINTAINER_ACCESS,
    "owner": gitlab.OWNER_ACCESS,
}

def get_repo(gl, project_id):
    return gl.projects.get(project_id)

def validate_config(config):
    if "server" not in config:
        config["server"] = SERVER
    if "gitlab_token" not in config:
        raise ValueError("missing GitLab token")

def add_user_to_repo(gl, repo, username, role):
    name = os.path.basename(repo.web_url)

    try:
        # Find user.
        user = gl.users.list(username=username)[0]
    except:
        # User doesn't exist.
        logging.warning(f"user {username} doesn\'t (yet) exist... skipping.")
        repo_ops["nouser"] += 1
        return False

    if not repo.members.list(query=username) and not repo.members.all(query=username):
        # If the user isn't a member of this repo and isn't a member of an
        # ancestor repo, then try to add the user as a reporter.
        try:
            repo.members.create({
                "user_id": user.id,
                "access_level": roles[role],
            })
            logging.info(f"{username} added as {role} for {name}.")
            repo_ops["access_created"] += 1
        except:
            logging.error(f"unable to make {username} a reporter for {name}.")
            repo_ops["error"] += 1
            return False
    else:
        # If the user is a member of this repo or a member of an ancestor repo,
        # then try to update the user's access.
        try:
            member = repo.members.all(query=username)[0]
            if member.access_level != gitlab.REPORTER_ACCESS:
                if member.access_level > gitlab.REPORTER_ACCESS:
                    logging.warning(f"{username} has higher access than reporter for {name}.")
                    return True
                member.access_level = gitlab.REPORTER_ACCESS
                member.save()
                logging.info(f"{username} given reporter access for {name}.")
                repo_ops["access_updated"] += 1
            else:
                logging.info(f"{username} is already a reporter for {name}.")
        except:
            logging.error(f"{username} not given reporter access for {name}.")
            repo_ops["error"] += 1
            return False

    return True

def add_users_to_repos(gl, repoids, role):
    ok = True
    reader = csv.reader(sys.stdin, delimiter=',')
    writer = csv.writer(sys.stdout, delimiter=',')

    for row in reader:
        _, _, cruzid, _ = row

        for repo_id in repoids:
            repo = get_repo(gl, repo_id)
            if not repo:
                logging.error("invalid repo id")
                repo_ops["error"] += 1
                ok = False
                continue

            if not add_user_to_repo(gl, repo, cruzid, role):
                ok = False

        if ok:
            writer.writerow(row)

def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description=(
            "Adds students to a set of GitLab repos.\n"
            "Reads stdin for a CSV with rows formatted as [name, CanvasID, CruzID, repo].\n"
            "Outputs CSV rows of students that were added to stdout.\n"
        )
    )
    parser.add_argument(
        "-v", "--verbose", default=False, action="store_true",
        help="print verbose statistics to stderr"
    )
    parser.add_argument(
        "-l", "--logging-level", default="INFO",
        choices=['debug', 'info', 'warning', 'error', 'critical', 'off'],
        help="set logging level for logs to stderr (default: info)"
    )
    parser.add_argument(
        "-r", "--role", default="reporter",
        choices=['reporter', 'developer', 'maintainer', 'owner'],
        help="set GitLab role for added students (default: reporter)"
    )
    parser.add_argument(
        "repoids", nargs="*", default=[],
        help="list of repo project IDs to add to"
    )
    args = parser.parse_args()

    if args.logging_level == "off":
        logging.disable(logging.CRITICAL)
    else:
        logging.basicConfig(
            stream=sys.stderr, level=args.logging_level.upper(),
            format="[%(levelname)s] %(message)s"
        )

    # Load the configuration.
    try:
        config = toml.load(os.environ["GCU_CONFIG"])
    except KeyError:
        logging.error("missing GCU_CONFIG environment variable")
        sys.exit(1)

    # Validate the configuration.
    try:
        validate_config(config)
    except ValueError as err:
        logging.error(err)
        sys.exit(1)

    # Authenticate the token.
    try:
        gl = gitlab.Gitlab(config["server"], config["gitlab_token"], api_version="4")
        gl.auth()
    except:
        logging.error("invalid GitLab token")
        sys.exit(1)

    add_users_to_repos(gl, args.repoids, args.role)

    # Print statistics of adding students to resource repo.
    if args.verbose:
        print('Overall statistics:', file=sys.stderr)
        for k in sorted(repo_ops.keys()):
            print(f" - {k}: {repo_ops[k]}", file=sys.stderr)

if __name__ == "__main__":
    main()
