.TH clone 1 "" "" gitlab-canvas-utils

.SH NAME
clone - Clones student GitLab repos

.SH SYNOPSIS
.B clone [OPTIONS]

.SH DESCRIPTION
Clones student repos, pulling them if already cloned.
Reads \fBstdin\fP for a CSV with rows formatted as \fB[name, CanvasID, CruzID,
repo]\fP.
Outputs CSV rows of students whose repos were cloned/pulled out to \fBstdout\fP.

.SH OPTIONS
.TP
.BR -h ", " --help
show program help and exit

.TP
.BR -r " " REPODIR ", " --repodir=REPODIR
the directory to clone the repos into (default: \fB/tmp/repos\fP).\fP

.TP
.BR -l " " LEVEL ", " --logging-level=LEVEL " " (default: " " info)
set logging level for logs to \fBstderr\fP (choices: \fBdebug\fP, \fBinfo\fP,
\fBwarning\fP, \fBerror\fP, \fBcritical\fP, \fBoff\fP).

.SH SEE ALSO
addtorepos(1),
checkout(1),
createrepos(1),
pushfiles(1),
rmfiles(1),
roster(1)
