.TH createrepos 1 "" "" gitlab-canvas-utils

.SH NAME
createrepos - Creates GitLab repos for students

.SH SYNOPSIS
.B createrepos [OPTIONS]

.SH DESCRIPTION
Creates GitLab repos for students.
The repos are created under the configured base repo path.
The group and subgroups in the path are created if they don't exist.
Supports the creation of both individual repos and shared repos.
Reads \fBstdin\fP for a CSV with rows formatted as \fB[name, CanvasID, CruzID,
repo]\fP.
Outputs CSV rows of students whose repos were created out to \fBstdout\fP.
Row output only occurs when creating individual repos.


.SH OPTIONS
.TP
.BR -h ", " --help
show program help and exit

.TP
.BR -s ", " --shared
specify that shared repositories for students should be created instead of
individual repos

.TP
.BR -u ", " --remove-unlisted
remove unlisted students from shared repos if any are found

.TP
.BR -v ", " --verbose
print verbose statistics to \fBstderr\fP

.TP
.BR -r " " ROLE ", " --role=ROLE " " (default: " " developer)
set student GitLab role (choices: \fBreporter\fP, \fBdeveloper\fP,
\fBmaintainer\fP, \fBowner\fP)

.TP
.BR -l " " LEVEL ", " --logging-level=LEVEL " " (default: " " info)
set logging level for logs to \fBstderr\fP (choices: \fBdebug\fP, \fBinfo\fP,
\fBwarning\fP, \fBerror\fP, \fBcritical\fP, \fBoff\fP)

.SH SEE ALSO
addtorepos(1),
checkout(1),
clone(1),
pushfiles(1),
rmfiles(1),
rmfromrepos(1),
roster(1)
