.TH rmfiles 1 "" "" gitlab-canvas-utils

.SH NAME
rmfiles - removes a set of files from student repos

.SH SYNOPSIS
.B rmfiles [OPTIONS] [list of files]

.SH DESCRIPTION
Removes a set of files from student repos.
The student repos to remove the files from must be cloned.
Unless otherwise specified, the repos are assumed to be cloned under
\fB/tmp/repos\fP.
Reads \fBstdin\fP for a CSV with rows formatted as \fB[name, CanvasID, CruzID,
repo]\fP.
Outputs CSV rows of students whose repos have been updated to \fBstdout\fP.

.SH OPTIONS
.TP
.BR -h ", " --help
show program help and exit

.TP
.BR -c " " COMMIT_MESSAGE ", " --commit-message=COMMIT_MESSAGE
the commit message for files to push

.TP
.BR -r " " REPODIR ", " --repodir=REPODIR
the directory that contains the cloned repos (default: \fB/tmp/repos\fP)

.TP
.BR -v ", " --verbose
print verbose statistics to \fBstderr\fP

.TP
.BR -l " " LEVEL ", " --logging-level=LEVEL " " (default: " " info)
set logging level for logs to \fBstderr\fP (choices: \fBdebug\fP, \fBinfo\fP,
\fBwarning\fP, \fBerror\fP, \fBcritical\fP, \fBoff\fP)

.SH SEE ALSO
addtorepos(1),
checkout(1),
clone(1),
createrepos(1),
pushfiles(1),
roster(1)
